package com.tangoplus.tangoq.db

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "t_measure_dynamic")
data class MeasureDynamic(
    @PrimaryKey(autoGenerate = true) var mobile_sn: Int = 0,
    val server_sn: Int? = null, // info의 sn을 말하는 거.
    val device_sn: Int = 0,
    val local_sn: Int = 1,
    val measure_sn: Int = 1,


    val user_uuid: String = "",
    val user_sn: Int = 0,
    val user_name: String = "",
    val measure_seq: Int = 2,
    val measure_type: Int = 7,
    val reg_date: String = "",
    val measure_start_time: String = "",
    val measure_end_time: String = "",
    val measure_photo_file_name: String,
    val measure_server_json_name: String? = null,
    val measure_server_file_name: String? = null,
    val measure_overlay_width: Int = 0,
    val measure_overlay_height: Int = 0,
    val measure_overlay_scale_factor_x: Float = 0F,
    val measure_overlay_scale_factor_y: Float = 0F,


    val ohs_front_horizontal_angle_elbow: Float = 0F,
    val ohs_front_horizontal_distance_elbow: Float = 0F,
    val ohs_front_horizontal_angle_shoulder: Float = 0F,
    val ohs_front_horizontal_distance_shoulder: Float = 0F,
    val ohs_front_horizontal_angle_hip: Float = 0F,
    val ohs_front_horizontal_distance_hip: Float = 0F,
    val ohs_front_horizontal_distance_center_left_hip: Float = 0F,
    val ohs_front_horizontal_distance_center_right_hip: Float = 0F,
    val ohs_front_horizontal_angle_knee: Float = 0F,
    val ohs_front_horizontal_distance_knee: Float = 0F,
    val ohs_front_horizontal_distance_center_left_knee: Float = 0F,
    val ohs_front_horizontal_distance_center_right_knee: Float = 0F,
    val ohs_front_horizontal_distance_center_left_toe: Float = 0F,
    val ohs_front_horizontal_distance_center_right_toe: Float = 0F,
    val ohs_front_vertical_angle_wrist_elbow_shoulder_left: Float = 0F,
    val ohs_front_vertical_angle_wrist_elbow_shoulder_right: Float = 0F,
    val ohs_front_vertical_angle_wrist_elbow_left: Float = 0F,
    val ohs_front_vertical_angle_wrist_elbow_right: Float = 0F,
    val ohs_front_vertical_angle_elbow_shoulder_left: Float = 0F,
    val ohs_front_vertical_angle_elbow_shoulder_right: Float = 0F,
    val ohs_front_vertical_angle_hip_knee_toe_left: Float = 0F,
    val ohs_front_vertical_angle_hip_knee_toe_right: Float = 0F,
    val ohs_front_vertical_angle_hip_knee_left: Float = 0F,
    val ohs_front_vertical_angle_hip_knee_right: Float = 0F,
    val ohs_front_vertical_angle_knee_toe_left: Float = 0F,
    val ohs_front_vertical_angle_knee_toe_right: Float = 0F,
    val ohs_front_vertical_angle_ankle_toe_left: Float = 0F,
    val ohs_front_vertical_angle_ankle_toe_right: Float = 0F,
    val ohs_front_vertical_angle_knee_ankle_toe_left: Float = 0F,
    val ohs_front_vertical_angle_knee_ankle_toe_right: Float = 0F,
    val ohs_front_horizontal_angle_wrist: Float = 0F,
    val ohs_front_horizontal_distance_wrist: Float = 0F,
    val ohs_front_horizontal_distance_center_left_wrist: Float = 0F,
    val ohs_front_horizontal_distance_center_right_wrist: Float = 0F,
    val ohs_front_horizontal_angle_mid_finger_tip: Float = 0F,
    val ohs_front_horizontal_distance_mid_finger_tip: Float = 0F,
    val ohs_front_horizontal_distance_center_mid_finger_tip_left: Float = 0F,
    val ohs_front_horizontal_distance_center_mid_finger_tip_right: Float = 0F,
    val ohs_side_left_angle_wrist_shoulder: Float = 0F,
    val ohs_side_left_angle_shoulder_hip: Float = 0F,
    val ohs_side_left_angle_wrist_shoulder_hip: Float = 0F,
    val ohs_side_left_angle_knee_ankle: Float = 0F,
    val ohs_side_left_angle_shoulder_hip_knee: Float = 0F,
    val ohs_side_left_angle_hip_knee_ankle: Float = 0F,
    val ohs_side_left_angle_knee_ankle_toe: Float = 0F,
    val ohs_side_right_angle_wrist_shoulder: Float = 0F,
    val ohs_side_right_angle_shoulder_hip: Float = 0F,
    val ohs_side_right_angle_wrist_shoulder_hip: Float = 0F,
    val ohs_side_right_angle_knee_ankle: Float = 0F,
    val ohs_side_right_angle_shoulder_hip_knee: Float = 0F,
    val ohs_side_right_angle_hip_knee_ankle: Float = 0F,
    val ohs_side_right_angle_knee_ankle_toe: Float = 0F,
    val ohs_back_horizontal_angle_wrist: Float = 0F,
    val ohs_back_horizontal_distance_wrist: Float = 0F,
    val ohs_back_horizontal_angle_shoulder: Float = 0F,
    val ohs_back_horizontal_distance_shoulder: Float = 0F,
    val ohs_back_horizontal_angle_hip: Float = 0F,
    val ohs_back_horizontal_distance_hip: Float = 0F,
    val ohs_back_horizontal_angle_knee: Float = 0F,
    val ohs_back_horizontal_distance_knee: Float = 0F,
    val ohs_back_horizontal_distance_center_wrist_left: Float = 0F,
    val ohs_back_horizontal_distance_center_wrist_right: Float = 0F,
    val ohs_back_horizontal_distance_center_hip_left: Float = 0F,
    val ohs_back_horizontal_distance_center_hip_right: Float = 0F,
    val ohs_back_horizontal_distance_center_knee_left: Float = 0F,
    val ohs_back_horizontal_distance_center_knee_right: Float = 0F,
    val ohs_back_horizontal_angle_mid_finger_tip: Float = 0F,
    val ohs_back_horizontal_distance_mid_finger_tip: Float = 0F,
    val ohs_back_horizontal_distance_center_mid_finger_tip_left: Float = 0F,
    val ohs_back_horizontal_distance_center_mid_finger_tip_right: Float = 0F,
    val ohs_back_vertical_angle_knee_heel_left: Float = 0F,
    val ohs_back_vertical_angle_knee_heel_right: Float = 0F,
    val ohs_back_vertical_angle_knee_ankle_heel_left: Float = 0F,
    val ohs_back_vertical_angle_knee_ankle_heel_right: Float = 0F,

    val ols_front_left_horizontal_angle_shoulder: Float = 0F,
    val ols_front_left_horizontal_distance_shoulder: Float = 0F,
    val ols_front_left_horizontal_angle_hip: Float = 0F,
    val ols_front_left_horizontal_distance_hip: Float = 0F,
    val ols_front_left_vertical_angle_hip_knee: Float = 0F,
    val ols_front_left_vertical_angle_knee_toe: Float = 0F,
    val ols_front_left_vertical_angle_hip_knee_toe: Float = 0F,
    val ols_front_left_vertical_angle_hip_knee_opposite: Float = 0F,
    val ols_front_left_vertical_angle_knee_toe_opposite: Float = 0F,
    val ols_front_left_vertical_angle_hip_knee_toe_opposite: Float = 0F,
    val ols_front_left_vertical_distance_toe_opposite_toe: Float = 0F,
    val ols_front_right_horizontal_angle_shoulder: Float = 0F,
    val ols_front_right_horizontal_distance_shoulder: Float = 0F,
    val ols_front_right_horizontal_angle_hip: Float = 0F,
    val ols_front_right_horizontal_distance_hip: Float = 0F,
    val ols_front_right_vertical_angle_hip_knee: Float = 0F,
    val ols_front_right_vertical_angle_knee_toe: Float = 0F,
    val ols_front_right_vertical_angle_hip_knee_toe: Float = 0F,
    val ols_front_right_vertical_angle_hip_knee_opposite: Float = 0F,
    val ols_front_right_vertical_angle_knee_toe_opposite: Float = 0F,
    val ols_front_right_vertical_angle_hip_knee_toe_opposite: Float = 0F,
    val ols_front_right_vertical_distance_toe_opposite_toe: Float = 0F,

    var uploaded: String = "0",
    val upload_date: String = "",
    val result_index: Int = 0,
    val uploaded_json: String = "0",
    val uploaded_file: String = "0",
    val uploaded_json_fail: String = "0",
    val used: String = "0",
)